# Generated by Django 2.2.2 on 2019-06-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='full_name',
            field=models.CharField(default='ОщJohn Street Doe', max_length=255, verbose_name='ФИО автора'),
            preserve_default=False,
        ),
    ]
